name: swiss_army_llama_service_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - aioredis
  - aioredlock
  - aiosqlite
  - faiss-cpu
  - fast_vector_similarity
  - fastapi
  - faster-whisper
  - filelock
  - httpx
  - langchain
  - langchain-community
  - llama-cpp-python
  - magika
  - mutagen
  - nvgpu
  - pandas
  - psutil
  - pydantic
  - PyPDF2
  - pytest
  - python-decouple
  - python-multipart
  - pytz
  - sqlalchemy
  - textract-py3
  - uvicorn
  - uvloop
